### ISSUE TITLE
poker related project

### ISSUE THREAD

**Issue by minqin** [yeahbah/Poker-Game#27]
hey, is there a way to contact you?

**Comment by yeahbah** [comment]
What's going on

**Comment by minqin** [comment]
I have a poker related project, want to check if you are interested

**Comment by yeahbah** [comment]
What's it about

**Comment by minqin** [comment]
AI poker bot

**Comment by yeahbah** [comment]
Not for me.

**Comment by minqin** [comment]
OK, never mind
